# Replace enter_your_token_here by readwise token you can generate at https://readwise.io/access_token
readwise_key: enter_your_token_here

# replace enter_your_key_here by mem api key you can generate at https://mem.ai/flows/api or by clicking Flows than Api - configure
mem_key: enter_your_key_here

# you can change the timestamp format below, just Change this date to the format you'd like: 01/02 03:04:05PM ‘06 -0700, per example: Mon Jan 2 15:04:05 MST 2006 
timestamp_format: Mon Jan _2 15:04. There is a good explanation at https://yourbasic.org/golang/format-parse-string-time-date-example/


## You can change the template for book and for highlight below. Make sure you keep the 2 leading spaces on each line and the two blank lines between. See README.md or the github repo for instructions and valid fields

book_template: |
  # {{.Title}}
  #{{.Category}} #readwise
  Author: {{.Author}}
  ![Cover]({{.CoverImageUrl}})
  {{if .SourceUrl}} src: {{.SourceUrl}} {{end}}


highlight_template: |
  # {{.Book.MemURL}} highlights
  #highlights synced on {{.TimeStamp}}
  {{range .Highlight}}- {{.Text}}{{range .Tags}} #{{.Name}}{{end}}{{if .Note}}
    - {{.Note}}{{end}}
  {{end}}

